In [2]:
import numpy as np
v =  np.random.randint(1,20,(15,))
arr = v.reshape(3,5)
print(arr.shape)
print(arr)
row_max = arr.max(axis=1).reshape(-1,1)
arr = np.where(arr == row_max, 0, arr)
print('\n',arr)

(3, 5)
[[13  8 13 16 19]
 [ 9 18  6 16 11]
 [ 6 13 19  1  9]]

 [[13  8 13 16  0]
 [ 9  0  6 16 11]
 [ 6 13  0  1  9]]


In [3]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 5, 7]], np.int32)
print('Shape:', x.shape)
print('Type:', type(x))
print('Data type:', x.dtype)

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [4]:
from numpy import linalg as LA
mat = np.array([[3, -2], [1, 0]], np.int32)
w, v = LA.eig(mat)
print('Eigenvalues:', w)
print('\nRight eigenvectors:\n', v)

Eigenvalues: [2. 1.]

Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [5]:
n = np.array([[0, 1, 2], [3, 4, 5]])
res = np.trace(n)
print('Sum of diagonal elements:', res)

Sum of diagonal elements: 4


In [10]:
m = np.arange(1,7).reshape(3,2)
print("reshape 3,2\n",m)
m = m.reshape(2,3)
print("reshape 2,3\n",m)

reshape 3,2
 [[1 2]
 [3 4]
 [5 6]]
reshape 2,3
 [[1 2 3]
 [4 5 6]]
